# Generated by Django 6.1.1 on 2026-09-23 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='ambient_pressure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='approved_signatory',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='certificate',
            name='calibrated_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='certificate',
            name='calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='condition_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='device_accuracy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='device_manufacturer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='certificate',
            name='device_resolution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='device_serial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='lab_humidity',
            field=models.CharField(blank=True, help_text='e.g. 45 ± 10 %RH', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='lab_temperature',
            field=models.CharField(blank=True, help_text='e.g. 23 ± 2 °C', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='reference_procedure',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='certificate',
            name='temperature_variation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='working_standard_certificate_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='working_standard_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='certificate',
            name='working_standard_serial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='CalibrationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_no', models.CharField(blank=True, help_text='e.g. 1, 2, 3 or a nominal point label', max_length=20)),
                ('applied_value', models.CharField(blank=True, max_length=50)),
                ('standard_reading', models.CharField(blank=True, max_length=50)),
                ('uut_reading', models.CharField(blank=True, help_text='Unit-under-test reading', max_length=50)),
                ('error', models.CharField(blank=True, max_length=50)),
                ('uncertainty', models.CharField(blank=True, max_length=50)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labmanager.certificate')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
