# Generated by Django 6.1.1 on 2026-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0002_certificate_ambient_pressure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationresult',
            name='error',
        ),
        migrations.RemoveField(
            model_name='calibrationresult',
            name='point_no',
        ),
        migrations.RemoveField(
            model_name='calibrationresult',
            name='standard_reading',
        ),
        migrations.RemoveField(
            model_name='calibrationresult',
            name='uut_reading',
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='deviation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Deviation (A-M)'),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='downward_reading',
            field=models.CharField(blank=True, max_length=50, verbose_name='Downward (M2)'),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='mean_value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mean Value (M)'),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='remarks',
            field=models.CharField(blank=True, default='Pass', max_length=20, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='upward_reading',
            field=models.CharField(blank=True, max_length=50, verbose_name='Upward (M1)'),
        ),
        migrations.AlterField(
            model_name='calibrationresult',
            name='applied_value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Applied Pressure (A)'),
        ),
        migrations.AlterField(
            model_name='calibrationresult',
            name='uncertainty',
            field=models.CharField(blank=True, max_length=50, verbose_name='Expanded Uncertainty (% FS)'),
        ),
    ]
