# Generated by Django 6.1.1 on 2026-09-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0003_remove_calibrationresult_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblineitem',
            name='calibration_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joblineitem',
            name='calibration_validity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joblineitem',
            name='reference_procedure',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='calibrationresult',
            name='remarks',
            field=models.CharField(blank=True, max_length=20, verbose_name='Remarks'),
        ),
    ]
