# Generated by Django 6.1.1 on 2026-09-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0004_joblineitem_calibration_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblineitem',
            name='reference_procedure',
            field=models.CharField(blank=True, choices=[('LCP/AAF/001', 'LCP/AAF/001'), ('LCP/AAF/002', 'LCP/AAF/002'), ('LCP/AAF/003', 'LCP/AAF/003'), ('LCP/AAF/004', 'LCP/AAF/004'), ('LCP/AAF/005', 'LCP/AAF/005')], max_length=150),
        ),
    ]
