# Generated by Django 6.1.1 on 2026-09-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0005_alter_joblineitem_reference_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblineitem',
            name='calibration_points',
        ),
        migrations.RemoveField(
            model_name='joblineitem',
            name='calibration_validity',
        ),
        migrations.RemoveField(
            model_name='joblineitem',
            name='reference_procedure',
        ),
        migrations.AddField(
            model_name='job',
            name='calibration_points',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='calibration_validity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='reference_procedure',
            field=models.CharField(blank=True, choices=[('LCP/AAF/001', 'LCP/AAF/001'), ('LCP/AAF/002', 'LCP/AAF/002'), ('LCP/AAF/003', 'LCP/AAF/003'), ('LCP/AAF/004', 'LCP/AAF/004'), ('LCP/AAF/005', 'LCP/AAF/005')], max_length=150),
        ),
    ]
