# Generated by Django 6.1.1 on 2026-09-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0007_remove_job_calibration_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblineitem',
            name='range',
        ),
        migrations.AddField(
            model_name='joblineitem',
            name='range_from',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='joblineitem',
            name='range_to',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
