# Generated by Django 6.1.1 on 2026-09-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0008_remove_joblineitem_range_joblineitem_range_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblineitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('bar', 'bar'), ('psi', 'psi'), ('kPa', 'kPa'), ('MPa', 'MPa'), ('kg/cm2', 'kg/cm2')], max_length=50, null=True),
        ),
    ]
