# Generated by Django 6.1.1 on 2026-09-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0009_joblineitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblineitem',
            name='calibration_points',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
