# Generated by Django 6.1.1 on 2026-09-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0010_alter_joblineitem_calibration_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='device_ratio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
