# Generated by Django 6.1.1 on 2026-09-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0011_certificate_device_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='device_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='device_resolution',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
