# Generated by Django 6.1.1 on 2026-09-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0012_alter_certificate_device_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='device_ratio',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='device_resolution',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
