# Generated by Django 6.1.1 on 2026-09-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0013_alter_certificate_device_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationresult',
            name='accutech_cmc',
            field=models.CharField(blank=True, max_length=50, verbose_name='Accutech CMC (% of FSD)'),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='combined_std_uncertainty',
            field=models.CharField(blank=True, max_length=50, verbose_name='Combined Std. Uncertainty'),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='expanded_uncertainty',
            field=models.CharField(blank=True, max_length=50, verbose_name='Expanded Uncertainty'),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='expanded_uncertainty_percent',
            field=models.CharField(blank=True, max_length=50, verbose_name='Expanded Uncertainty (% of FSD)'),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='hysteresis',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hysteresis'),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='max_expanded_uncertainty',
            field=models.CharField(blank=True, max_length=50, verbose_name='Max Expanded Un. (% of FSD)'),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='repeatability',
            field=models.CharField(blank=True, max_length=50, verbose_name='Repeatability'),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='std_unc_hysteresis',
            field=models.CharField(blank=True, max_length=50, verbose_name='Std. Un. for Hysteresis'),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='std_unc_press_tx',
            field=models.CharField(blank=True, max_length=50, verbose_name='Std. Un. for Press Tx'),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='uncertainty_resolution',
            field=models.CharField(blank=True, max_length=50, verbose_name='Un. due to Resolution'),
        ),
    ]
