# Generated by Django 6.1.1 on 2026-09-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0014_calibrationresult_accutech_cmc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationresult',
            name='accutech_cmc',
        ),
        migrations.RemoveField(
            model_name='calibrationresult',
            name='combined_std_uncertainty',
        ),
        migrations.RemoveField(
            model_name='calibrationresult',
            name='expanded_uncertainty',
        ),
        migrations.RemoveField(
            model_name='calibrationresult',
            name='expanded_uncertainty_percent',
        ),
        migrations.RemoveField(
            model_name='calibrationresult',
            name='hysteresis',
        ),
        migrations.RemoveField(
            model_name='calibrationresult',
            name='max_expanded_uncertainty',
        ),
        migrations.RemoveField(
            model_name='calibrationresult',
            name='repeatability',
        ),
        migrations.RemoveField(
            model_name='calibrationresult',
            name='std_unc_hysteresis',
        ),
        migrations.RemoveField(
            model_name='calibrationresult',
            name='std_unc_press_tx',
        ),
        migrations.RemoveField(
            model_name='calibrationresult',
            name='uncertainty_resolution',
        ),
    ]
