# Generated by Django 6.1.1 on 2026-09-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0015_remove_calibrationresult_accutech_cmc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationresult',
            name='pressure_media',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='reference_instrument_range',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='uuc_full_scale',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='calibrationresult',
            name='uuc_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='pressure_media',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='certificate',
            name='reference_instrument_range',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='uuc_full_scale',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='uuc_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
