# Generated by Django 6.1.1 on 2026-09-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0016_calibrationresult_pressure_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='lab_humidity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='lab_temperature',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
