# Generated by Django 6.1.1 on 2026-09-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0018_alter_calibrationresult_reference_instrument_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='re_calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
