# Generated by Django 6.1.1 on 2026-09-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0019_certificate_re_calibration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='device_tag_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
