# Generated by Django 6.1.1 on 2026-09-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0020_certificate_device_tag_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblineitem',
            name='calibration_validity',
        ),
        migrations.AddField(
            model_name='joblineitem',
            name='calibration_validity_unit',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], default='years', max_length=10),
        ),
        migrations.AddField(
            model_name='joblineitem',
            name='calibration_validity_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Calibration Validity'),
        ),
    ]
