# Generated by Django 6.1.1 on 2026-09-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0021_remove_joblineitem_calibration_validity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('head', 'Lab Head'), ('technician', 'Lab Technician')], default='head', max_length=20),
        ),
    ]
