# Generated by Django 6.1.1 on 2026-10-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0022_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='condition_notes',
        ),
        migrations.AddField(
            model_name='certificate',
            name='instrument_adjusted',
            field=models.BooleanField(default=False, verbose_name='Instrument is adjusted and post adjustment values are reported'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='instrument_received_good',
            field=models.BooleanField(default=True, verbose_name='Instrument is received in good condition'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='no_adjustment',
            field=models.BooleanField(default=True, verbose_name='No adjustment is carried out and measurements in this certificate are as received figures'),
        ),
    ]
