# Generated by Django 6.1.1 on 2026-10-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0024_certificate_approval_status_certificate_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='certificate',
            name='device_accuracy_unit',
            field=models.CharField(blank=True, choices=[('FS', 'FS'), ('Rdg', 'Rdg')], default='FS', max_length=10),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
