# Generated by Django 6.1.1 on 2026-10-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0025_remove_certificate_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='datasheet_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='stem_length_test_pressure',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stem Length / Test Pressure'),
        ),
        migrations.AddField(
            model_name='job',
            name='customer_fax',
            field=models.CharField(blank=True, max_length=50, verbose_name='FAX'),
        ),
        migrations.AddField(
            model_name='job',
            name='customer_tel',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=250, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='scope_of_work',
            field=models.CharField(blank=True, max_length=250, verbose_name='Scope of Work'),
        ),
    ]
