# Generated by Django 6.1.1 on 2026-10-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0026_certificate_datasheet_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='customer_tel',
            field=models.TextField(blank=True, max_length=50, verbose_name='Telephone'),
        ),
    ]
