# Generated by Django 6.1.1 on 2026-10-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0027_alter_job_customer_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='datasheet_number',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='stem_length_test_pressure',
        ),
        migrations.RemoveField(
            model_name='job',
            name='customer_fax',
        ),
        migrations.RemoveField(
            model_name='job',
            name='customer_tel',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='scope_of_work',
        ),
    ]
