# Generated by Django 6.1.1 on 2026-10-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0028_remove_certificate_datasheet_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='datasheet_number',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='fax_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='scope_of_work',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
