# Generated by Django 6.1.1 on 2026-10-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0029_job_datasheet_number_job_fax_number_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, choices=[('Lab', 'Lab'), ('On-site', 'On-site')], max_length=200),
        ),
    ]
