# Generated by Django 6.1.1 on 2026-10-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmanager', '0030_alter_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='datasheet_number',
        ),
        migrations.AddField(
            model_name='certificate',
            name='datasheet_number',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
